hello_homepage:
    path:     /hello/{name}/{sex}
#    path:     /hello/{name}
    defaults: { _controller: HelloBundle:Hello:index , requirements : sex : h|f}
#    defaults: { _controller: HelloBundle:Hello:hello }


